({
    shouldDeps:[
        {
            elems:['services']
        },
        'services',
        {
            elems:['contacts']
        },
        'contacts',
        {
            elems:['vkladka']
        },
        'vkladka',
        {
            elems:['department']
        },
        'department',
        {
            elems:['news']
        },
        'news',
        {
            elems:['documents']
        },
        'documents',
    ]
})