block('main')({
    content: (
        {
            cls:'container',
            content:{
                elem:'tabs',
                tag:'nav',
                content:[
                    {
                        elem:'services',
                        mix:{elem:'tab'}
                    },
                    {
                        elem:'contacts',
                        mix:{elem:'tab'}
                    },
                ]
            }
        }
    )
});