block('card')({
    content: (
        [
            {   
                block:'main',
                elem:'menu',
                cls:'container',
                content:{
                    elem:'nav',
                    tag:'nav',
                    content:[
                        {   
                            elem:'nav-item',
                            tag:'a',
                            content:'Услуги',
                            attrs:{
                                href:'/'
                            }
                        },
                        {   
                            elem:'nav-item',
                            tag:'a',
                            content:'Вкладка',
                        },
                        {   
                            elem:'nav-item',
                            tag:'a',
                            content:'Контакты'
                        },
                        {   
                            elem:'nav-item',
                            tag:'a',
                            content:'Новости и акции'
                        },
                        {   
                            elem:'nav-item',
                            tag:'a',
                            content:'Отделения'
                        },
                        {   
                            elem:'nav-item',
                            tag:'a',
                            content:'Нормативные документы'
                        }
                    ]
                }
            },
            {
                cls:'container',
                content:
                [
                    {
                        block:'services',
                        elem:'roads',
                        content:'Поликлиника №1›Платные услуги › Услуги'
                    },
                    {
                        elem:'body',
                        cls:'row',
                        content:[
                            {
                                cls:'col',
                                content:{
                                    elem:'content'
                                }
                            }
                            ,
                            {
                                cls:'col-auto',
                                content:{
                                    elem:'directory',
                                    content:'тут будет колонка'
                                }
                            }
                        ]
                    }
                ]
            }
        ]
        
    )
});